"""mcp.launcher — generate per-server wrapper scripts.

Spec: internal/spec-mcp-administration-2026-05-10.md §5.3 (Configure / credentials).

The wrapper-script pattern is the spec's chosen design for credential
binding: openclaw.json's ``mcp.servers[name].command`` points at a
generated bash script under ``{shared_dir}/mcp/launchers/<bot>/<server>``.
The script reads the bot's keystore at exec time, exports the env
variables the server expects, then exec's the real command. This keeps
secrets out of openclaw.json (which is git-backed up) and lets credential
rotation happen in one place (the keystore).

The scripts are owned by the bot's user (so OpenClaw can spawn them) and
written via the standard ``/tmp`` staging + ``sudo /bin/cp`` pattern
from CLAUDE.md when the target is in a bot-owned location, or directly
when staying under ``{shared_dir}`` (evolve-user-owned).

Phase B targets ``{shared_dir}/mcp/launchers/`` — under shared_dir,
evolve-user-owned, no sudo needed. The bot's user has read+execute
access via the standard ACL inheritance on {shared_dir}. The script
shells out to ``evolve-admin keystore get`` to resolve credentials at
exec time.
"""
from __future__ import annotations

import os
import shlex
import stat
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .catalog import CatalogEntry


def launchers_dir(shared_dir: Path) -> Path:
    return shared_dir / "mcp" / "launchers"


def launcher_path(shared_dir: Path, bot_id: str, server_id: str) -> Path:
    return launchers_dir(shared_dir) / bot_id / server_id


# ── Script generation ─────────────────────────────────────────────────────────

# Keystore CLI binary on the mini. Path matches the install location used
# by setup_wizard.py / evolve-admin. Override via env var for tests.
_KEYSTORE_CLI = os.environ.get(
    "EVOLVE_KEYSTORE_CLI",
    "/usr/local/bin/evolve-admin",
)


@dataclass
class LauncherSpec:
    """Inputs for generating a wrapper script.

    Attributes:
      catalog_entry: The vetted entry the install is based on.
      env_bindings:  Map of env-var-name → "keystore:<key-name>" reference.
                     Each key referenced must exist in the keystore at
                     exec time; otherwise the wrapper exits non-zero and
                     OpenClaw logs the failure.
    """

    catalog_entry: CatalogEntry
    env_bindings: dict[str, str]


def _shell_quote(s: str) -> str:
    return shlex.quote(s)


def render_script(spec: LauncherSpec, bot_id: str, server_id: str) -> str:
    """Render the wrapper-script bash source for a (bot, server) install.

    Pure function — exposed separately from write_launcher() so unit
    tests can snapshot the output without touching the filesystem.
    """
    entry = spec.catalog_entry
    if entry.transport != "stdio":
        raise ValueError(
            f"Wrapper-script credential binding is only for stdio servers; "
            f"got transport={entry.transport!r}. http/url servers should "
            "use header-based auth resolved at config-write time (Phase C)."
        )
    if not entry.command:
        raise ValueError("stdio catalog entry must have a command")

    # Compose the env-export block. Each binding line resolves keystore:<k>
    # at exec time and exits non-zero on failure so OpenClaw doesn't spawn
    # the server with a missing credential.
    env_lines: list[str] = []
    for var_name, ref in spec.env_bindings.items():
        if not ref.startswith("keystore:"):
            raise ValueError(
                f"env binding {var_name!r} must be of the form 'keystore:<key-name>'; "
                f"got {ref!r}"
            )
        key_name = ref.split(":", 1)[1]
        if not key_name:
            raise ValueError(f"env binding {var_name!r} has empty keystore key name")
        # Use the keystore CLI to fetch the value. Capture stderr to /dev/null
        # to keep MCP stdio clean if the lookup fails; exit propagates.
        env_lines.append(
            f"{var_name}=$({_shell_quote(_KEYSTORE_CLI)} keystore get "
            f"{_shell_quote(key_name)} 2>/dev/null)"
        )
        env_lines.append(
            f'if [ -z "${{{var_name}}}" ]; then '
            f'echo "evolve-mcp-launcher: missing keystore key {key_name!r} for {var_name}" >&2; '
            f'exit 64; fi'
        )
        env_lines.append(f"export {var_name}")

    args_quoted = " ".join(_shell_quote(a) for a in entry.args)
    command_quoted = _shell_quote(entry.command)

    env_block = "\n".join(env_lines) + ("\n" if env_lines else "")
    return (
        "#!/bin/bash\n"
        "# Auto-generated by Evolve mcp installer; do not edit.\n"
        f"# bot={bot_id} server={server_id} catalog={entry.id} "
        f"catalog_fingerprint={entry.fingerprint()[:12]}\n"
        "# Spec: internal/spec-mcp-administration-2026-05-10.md §5.3\n"
        "set -euo pipefail\n"
        f"{env_block}"
        f"exec {command_quoted}"
        f"{' ' + args_quoted if args_quoted else ''}"
        ' "$@"\n'
    )


# ── Filesystem operations ─────────────────────────────────────────────────────

def write_launcher(
    spec: LauncherSpec,
    bot_id: str,
    server_id: str,
    shared_dir: Path,
) -> Path:
    """Write the wrapper script for (bot_id, server_id).

    Atomic temp-file + rename. Chmod 0755 so the bot's user can execute.
    Returns the script's absolute path (suitable for use as
    ``mcp.servers[server_id].command`` in openclaw.json).
    """
    script = render_script(spec, bot_id, server_id)
    target = launcher_path(shared_dir, bot_id, server_id)
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(".tmp")
    tmp.write_text(script)
    # 0755 owner-rwx, group/other-rx — bot user inherits read+exec via
    # the bot's user being in the evolve group (set by setup_wizard).
    tmp.chmod(stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
    tmp.replace(target)
    return target


def delete_launcher(bot_id: str, server_id: str, shared_dir: Path) -> bool:
    """Remove a wrapper script. Returns True if deleted; False if absent."""
    target = launcher_path(shared_dir, bot_id, server_id)
    if not target.exists():
        return False
    target.unlink()
    return True


# ── HTTP-transport credential resolution ──────────────────────────────────────
#
# Phase B's wrapper-script pattern handles stdio servers, where the launcher
# can shell out to ``evolve-admin keystore get`` at exec time. HTTP-transport
# MCP servers don't have an exec point — openclaw.json's mcp.servers[id]
# carries ``url`` + ``headers`` directly and OpenClaw uses them as-is. So
# the install applier must resolve keystore references at apply time and
# write the literal header values into openclaw.json.
#
# Trade-off: HTTP server credentials end up in openclaw.json. This is the
# anti-pattern stdio avoids, but http leaves no alternative. Mitigations:
#   - Rotation requires an UpdateMcpServerConfig proposal (stdio rotates
#     in the keystore alone).
#   - openclaw.json is owned by the bot user, not world-readable.
#   - The keystore is still the source-of-truth for the secret; the
#     openclaw.json value is a derived cache.

def resolve_keystore_value(key_name: str, *, timeout: float = 5.0) -> tuple[str | None, str | None]:
    """Resolve a keystore reference by shelling out to ``evolve-admin keystore get``.

    Returns (value, error). On success error is None; on failure value is None.
    """
    import subprocess
    if not key_name:
        return None, "empty_key_name"
    try:
        r = subprocess.run(
            [_KEYSTORE_CLI, "keystore", "get", key_name],
            capture_output=True, text=True, timeout=timeout,
        )
    except (subprocess.TimeoutExpired, OSError) as exc:
        return None, f"{type(exc).__name__}: {exc}"
    if r.returncode != 0:
        return None, f"rc={r.returncode}: {r.stderr.strip()[:200]}"
    value = r.stdout.strip()
    if not value:
        return None, "empty_value"
    return value, None


def resolve_http_headers(
    catalog_entry: "CatalogEntry",
    env_bindings: dict[str, str],
) -> tuple[dict[str, str] | None, str | None]:
    """Build the ``headers`` dict to embed in openclaw.json for an http server.

    Each required_env entry becomes a header. ``env_bindings`` maps the
    required_env name → ``"keystore:<key>"``. The header *name* is taken
    from the required_env's ``name`` field (so the catalog entry can
    define ``Authorization`` as a required env and the resolved value
    becomes the literal header value).

    Returns (headers, error). On any keystore failure error is set and
    headers is None.
    """
    headers: dict[str, str] = {}
    required = catalog_entry.required_env or []
    for req in required:
        binding = env_bindings.get(req.name)
        if not binding:
            return None, f"missing binding for required header {req.name!r}"
        if not binding.startswith("keystore:"):
            return None, (
                f"http binding {req.name!r} must be 'keystore:<key>'; got {binding!r}"
            )
        key_name = binding.split(":", 1)[1]
        value, err = resolve_keystore_value(key_name)
        if value is None:
            return None, f"keystore get {key_name!r} failed: {err}"
        headers[req.name] = value
    return headers, None


# Allow CatalogEntry to be imported lazily for tests that don't need it.
try:
    from .catalog import CatalogEntry  # type: ignore  # noqa: F401 — type-hint only
except ImportError:  # pragma: no cover
    pass
