"""30-day rolling baseline for pod report v2 trending signals.

Reads `{shared_dir}/metrics/{date}/{bot}.json` files written by measure.py
and computes (mean, stddev, n) over a trailing window. The report's
trending bucket asks `is_anomaly(current, baseline)` rather than checking
fixed-$ thresholds.

Why per-bot files (not metrics/{date}/all.json):
  all.json is generated by measure.py at the start of the day; the per-bot
  files are written at end-of-day. all.json's pod totals are zero on the
  day-of and stale relative to per-bot data — verified live 2026-05-07.

Sparse-bot suppression:
  When a bot's 30d sample mean is below a noise floor (default: 3 sessions
  or $0.50 cost), small absolute swings produce huge ratios. The is_anomaly
  helper takes a `min_mean` guard so callers can suppress these cases.
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass
from datetime import date, timedelta
from pathlib import Path


@dataclass(frozen=True)
class Baseline:
    """Summary statistics over the trailing window for one (bot, metric) pair."""

    metric: str
    bot_id: str
    mean: float
    stddev: float
    n: int  # number of days with data (≤ window_days)

    @property
    def is_cold(self) -> bool:
        """True when we don't have enough samples to trust ratios.

        Below 14 days of data, callers should fall back to a stricter
        anomaly factor and label the line "(limited baseline)" so the
        reader knows.
        """
        return self.n < 14


def baseline_for_bot(
    metric: str,
    bot_id: str,
    shared_dir: Path,
    end_date: date,
    window_days: int = 30,
) -> Baseline:
    """Compute baseline for one (bot, metric) over `[end_date - window, end_date)`.

    The end date is exclusive — a baseline computed on 2026-05-07 looks at
    `metrics/2026-04-07/{bot}.json` through `metrics/2026-05-06/{bot}.json`.
    Excluding `end_date` means the value being judged isn't part of its own
    baseline.

    `metric` matches the field name in the per-bot daily metrics file.
    Common values: "session_count", "turn_count", "total_cost_estimated".

    Missing days (no metrics file written for that bot/date) are skipped,
    not zeroed — a bot that didn't run shouldn't count as "had zero".
    """
    values: list[float] = []
    for offset in range(1, window_days + 1):
        d = end_date - timedelta(days=offset)
        f = shared_dir / "metrics" / d.isoformat() / f"{bot_id}.json"
        if not f.exists():
            continue
        try:
            data = json.loads(f.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        v = data.get(metric)
        if v is None:
            continue
        try:
            values.append(float(v))
        except (TypeError, ValueError):
            continue

    n = len(values)
    if n == 0:
        return Baseline(metric=metric, bot_id=bot_id, mean=0.0, stddev=0.0, n=0)

    mean = sum(values) / n
    variance = sum((v - mean) ** 2 for v in values) / n if n > 1 else 0.0
    stddev = math.sqrt(variance)
    return Baseline(metric=metric, bot_id=bot_id, mean=mean, stddev=stddev, n=n)


def is_high_anomaly(
    current: float,
    baseline: Baseline,
    factor: float = 2.0,
    min_mean: float = 0.0,
) -> bool:
    """True when `current` is anomalously HIGH vs baseline.

    Two guards combine to suppress noise:
      - sigma guard: must exceed mean + 2σ. Catches cases where a noisy
        metric ratio-explodes on a near-zero mean.
      - min_mean guard: skip bots whose baseline mean is below the noise
        floor for this metric (e.g. mean < 3 sessions/day). Anything from
        0 to 5 on a tiny denominator is meaningless.

    Cold-start (n < 14) callers should pass a stricter `factor` (e.g. 3.0)
    and add "(limited baseline)" to the rendered line.
    """
    if baseline.n == 0 or baseline.mean < min_mean:
        return False
    sigma_threshold = baseline.mean + 2 * baseline.stddev
    if current < sigma_threshold:
        return False
    return current >= factor * baseline.mean


def is_low_anomaly(
    current: float,
    baseline: Baseline,
    factor: float = 0.3,
    min_mean: float = 0.0,
) -> bool:
    """True when `current` is anomalously LOW vs baseline.

    Mirrors is_high_anomaly. Used for "sessions dropped to 1/10 normal"
    detection. The sigma guard is `mean - 2σ`: don't flag a quiet day if
    quiet days are common.
    """
    if baseline.n == 0 or baseline.mean < min_mean:
        return False
    sigma_threshold = max(0.0, baseline.mean - 2 * baseline.stddev)
    if current > sigma_threshold:
        return False
    return current <= factor * baseline.mean


def ratio(current: float, baseline: Baseline) -> float:
    """current / baseline.mean, or 0.0 if mean is 0. Used for display."""
    if baseline.mean == 0:
        return 0.0
    return current / baseline.mean


def history_for_bot(
    metric: str,
    bot_id: str,
    shared_dir: Path,
    end_date: date,
    window_days: int = 30,
) -> list[tuple[str, float]]:
    """Return [(date_iso, value)] for each day with data, oldest-first.

    Used to render sparklines under trending lines. Missing days are not
    included (no zeros) — the renderer can decide whether to interpolate
    or render gaps. The end_date is exclusive, matching baseline_for_bot.
    """
    out: list[tuple[str, float]] = []
    for offset in range(window_days, 0, -1):  # oldest first
        d = end_date - timedelta(days=offset)
        f = shared_dir / "metrics" / d.isoformat() / f"{bot_id}.json"
        if not f.exists():
            continue
        try:
            data = json.loads(f.read_text())
            v = data.get(metric)
            if v is None:
                continue
            out.append((d.isoformat(), float(v)))
        except (OSError, json.JSONDecodeError, TypeError, ValueError):
            continue
    return out
