"""tests/test_cli_keystore_get.py — `evolve-admin keystore get <name>` CLI.

This command's caller is **shell scripts** generated by
packages/analyzer/mcp_admin/launcher.py at MCP-server exec time. The
launcher's contract (launcher.py:106-114) is:

    VAR=$(/usr/local/bin/evolve-admin keystore get <slot> 2>/dev/null)
    if [ -z "${VAR}" ]; then echo "missing..." >&2; exit 64; fi
    export VAR

So this command MUST:
  - print the raw value to stdout with no trailing newline (the env var
    must carry the exact secret, not value+'\\n')
  - exit non-zero with empty stdout on missing/empty key (shell guard
    treats empty stdout as failure)
  - never write the secret to stderr

These tests verify the contract via **actual subprocess invocation of
the click CLI** (not in-process click.testing.CliRunner), because the
real launcher subshells the binary. If anyone breaks this contract —
adds a newline, prints to stderr, returns 0 on missing — the launcher
fails silently in production while resolve_status_mcp lies and reports
'valid'. That's exactly what happened with the original CLI absence
documented in docs/skills-deep-audit-2026-05-30.md F1.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

_ADMIN_DIR = Path(__file__).parent.parent
_ANALYZER_DIR = _ADMIN_DIR.parent / "analyzer"
for p in (str(_ADMIN_DIR), str(_ANALYZER_DIR)):
    if p not in sys.path:
        sys.path.insert(0, p)


@pytest.fixture
def cli_env(tmp_path, monkeypatch):
    """Create an isolated shared dir + network.json so the CLI's
    KeystoreManager points at our test vault, not the real one.

    EVOLVE_FORCE_FILE_VAULT=1 is set BOTH in this process (so the
    in-process _seed_key() writes to the file vault) AND in the
    subprocess env (so the CLI under test also uses the file vault).
    Without both, seeding could land in the macOS Keychain while the
    CLI reads from the file vault (or vice versa) — silent miss.
    """
    shared = tmp_path / "shared"
    shared.mkdir()
    network = {
        "sharedDir": str(shared),
        "primary": "evo",
        "bots": {"team_bot_b": {"user": "personal_bot_user"}},
        "members": ["team_bot_b"],
    }
    network_path = tmp_path / "network.json"
    network_path.write_text(json.dumps(network))

    # Force the file-vault path (not macOS keychain) in THIS process — the
    # seeding helper imports keystore in-process and would otherwise hit
    # the real Keychain on macOS dev/CI hosts.
    monkeypatch.setenv("EVOLVE_FORCE_FILE_VAULT", "1")

    # And in the subprocess env — both reader and writer must agree on
    # which vault they're using.
    env = os.environ.copy()
    env["EVOLVE_FORCE_FILE_VAULT"] = "1"
    env["PYTHONPATH"] = f"{_ADMIN_DIR}{os.pathsep}{_ANALYZER_DIR}"
    return shared, network_path, env


def _seed_key(shared_dir: Path, name: str, value: str):
    """Register + set a key in the isolated keystore.

    Uses the KeystoreManager directly (faster than spawning two subprocesses
    just to populate test data). Relies on EVOLVE_FORCE_FILE_VAULT=1
    being set in os.environ (per the fixture) so seeding writes to the
    file-vault under shared_dir — which the subprocess CLI will then
    read from via the network.json::sharedDir we pass it.

    The XOR vault key at ~/.openclaw/.evolve-vault-key is naturally
    shared between the in-process seeder and the subprocess reader since
    they're the same machine, so we don't need to redirect it.
    """
    from evolve_admin.keystore import KeystoreManager

    mgr = KeystoreManager(shared_dir)
    mgr.register(name, provider="test", scope="shared",
                 description="cli get test", bots=None, value=value)


def _run_cli(args, env, network_path):
    """Spawn `python -m evolve_admin.cli ...` with the isolated env."""
    cmd = [
        sys.executable, "-m", "evolve_admin.cli",
        "--network", str(network_path),
        *args,
    ]
    return subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=15)


# ── Contract tests ──────────────────────────────────────────────────────


class TestKeystoreGetCliContract:
    """These tests pin the contract that the MCP launcher relies on.
    If any of them fail, every MCP-backed install fails silently in
    production."""

    def test_value_printed_to_stdout_with_no_trailing_newline(self, cli_env, monkeypatch):
        """The captured shell value must be the EXACT secret, not secret+\\n.
        Bash $(...) strips one trailing newline but more than one would
        change the env var's value silently."""
        shared, network_path, env = cli_env
        monkeypatch.setenv("EVOLVE_FORCE_FILE_VAULT", "1")
        _seed_key(shared, "test-slot", "ntn_real_secret_xyz")

        # Set the same forced-file-vault flag in the subprocess by
        # monkeypatching the module via a tiny conftest sibling — but
        # simpler: just set the env var the test relies on.
        result = _run_cli(["keystore", "get", "test-slot"], env, network_path)

        assert result.returncode == 0, (
            f"expected rc=0, got {result.returncode}; stderr={result.stderr!r}"
        )
        # CRITICAL: no trailing newline. The bash launcher captures via
        # VAR=$(...) which strips one trailing newline, but it does NOT
        # strip leading/embedded whitespace, and other consumers may
        # process the bytes verbatim. Defensive: emit exactly the value.
        assert result.stdout == "ntn_real_secret_xyz", (
            f"stdout must be the exact value with no trailing newline; "
            f"got {result.stdout!r}"
        )

    def test_missing_key_exits_nonzero_with_empty_stdout(self, cli_env):
        """The launcher's `[ -z "$VAR" ]` guard depends on empty stdout
        signaling failure. If we ever return rc=0 with empty stdout, the
        guard would still trip — but if we ever print SOMETHING (an error
        message, a "not found" string) to stdout, the guard would FALSELY
        succeed and the MCP server would exec with that string as the
        secret. Worst-case silent corruption."""
        shared, network_path, env = cli_env
        env["EVOLVE_FORCE_FILE_VAULT"] = "1"

        result = _run_cli(["keystore", "get", "nonexistent-slot"], env, network_path)

        assert result.returncode != 0, (
            f"missing key MUST exit non-zero; got rc={result.returncode} "
            f"stdout={result.stdout!r}"
        )
        assert result.stdout == "", (
            f"missing key MUST produce empty stdout (errors go to stderr); "
            f"got stdout={result.stdout!r}"
        )

    def test_empty_value_treated_as_missing(self, cli_env):
        """An empty stored value is just as broken as a missing key for
        the consumer — the bash guard can't tell them apart. Both should
        exit non-zero so the launcher fails fast."""
        shared, network_path, env = cli_env
        _seed_key(shared, "blank-slot", "")  # registered but blank

        result = _run_cli(["keystore", "get", "blank-slot"], env, network_path)

        assert result.returncode != 0, (
            f"empty-value key MUST exit non-zero; got rc={result.returncode}"
        )
        assert result.stdout == ""

    def test_value_with_special_characters_round_trips(self, cli_env):
        """Real secrets contain special characters (=, +, /, base64 padding,
        sometimes embedded shell metachars). The CLI must emit them
        verbatim, not shell-escape them — the launcher wraps the call in
        $(...) and exports the result; double-escaping would break the
        Authorization header at the MCP server."""
        shared, network_path, env = cli_env
        env["EVOLVE_FORCE_FILE_VAULT"] = "1"
        weird_secret = "lin_api_X+Y/Z=AbCd-1234_efgh.ijkl"
        _seed_key(shared, "weird-slot", weird_secret)

        result = _run_cli(["keystore", "get", "weird-slot"], env, network_path)

        assert result.returncode == 0
        assert result.stdout == weird_secret

    def test_json_blob_value_round_trips_exactly(self, cli_env):
        """Notion's keystore slot stores a JSON-encoded headers blob (see
        notion_install.build_headers_json). The CLI must preserve every
        byte — adding a newline at the end would change the JSON's
        deserialized result for some parsers, and escaping the quotes
        would make the env var unusable as JSON."""
        shared, network_path, env = cli_env
        env["EVOLVE_FORCE_FILE_VAULT"] = "1"
        json_blob = '{"Authorization":"Bearer ntn_xyz","Notion-Version":"2022-06-28"}'
        _seed_key(shared, "notion-team_bot_b", json_blob)

        result = _run_cli(["keystore", "get", "notion-team_bot_b"], env, network_path)

        assert result.returncode == 0
        assert result.stdout == json_blob
        # Sanity: the captured value should parse as JSON unchanged.
        parsed = json.loads(result.stdout)
        assert parsed["Authorization"] == "Bearer ntn_xyz"


# ── Regression guard for the original bug ──────────────────────────────


class TestKeystoreCommandExists:
    """The bug that motivated this whole audit: the launcher shelled out
    to `evolve-admin keystore get <slot>` but the CLI had no `keystore`
    command group. resolve_status_mcp reported 'valid' because it only
    checked slot presence, never tested the launcher pipeline. Five MCP
    skills (notion/linear/obsidian_vault/dropbox/github-MCP) silently
    failed in production until this fix landed.

    This regression test asserts the command exists and is reachable
    through the top-level CLI — if anyone refactors it away again, the
    same silent-failure class returns."""

    def test_keystore_group_is_registered_on_main(self):
        """The `keystore` subcommand must appear in `evolve-admin --help`."""
        from evolve_admin.cli import main

        # click's main is a Group; its subcommands include `keystore`.
        sub_names = list(main.commands.keys())
        assert "keystore" in sub_names, (
            f"`keystore` command group missing from CLI. "
            f"This is the bug from docs/skills-deep-audit-2026-05-30.md F1 — "
            f"every MCP launcher will silently exit 64 again."
        )

    def test_keystore_get_subcommand_exists(self):
        """The specific subcommand the launcher calls must exist."""
        from evolve_admin.cli import main

        keystore_group = main.commands["keystore"]
        assert "get" in keystore_group.commands, (
            f"`keystore get` subcommand missing. "
            f"Launcher contract (mcp_admin/launcher.py:106) calls "
            f"`evolve-admin keystore get <slot>` at MCP-server exec time."
        )
