"""EVO-LINUX-PHANTOM-GATEWAY residual — the orphan-sweeper on Linux.

PR #3120 stopped fresh evo-primary installs from PROVISIONING the legacy
``ai.openclaw.evolve-gateway`` duplicate. But the orphan-SWEEPER that would
auto-remove an ALREADY-EXISTING stale unit was launchd-only: it globbed
``/Library/LaunchDaemons`` and did nothing on Linux. A pod provisioned by the
old wizard (the live DigitalOcean evo-primary pod was one) therefore kept its
stale ``ai.openclaw.evolve-gateway.service`` on disk forever — it had to be
disabled and moved aside by hand.

These tests pin the Linux systemd path of ``find_orphaned_plists`` /
``remove_orphaned_plists``:

1. A stale ``ai.openclaw.evolve-gateway.service`` on an evo-primary pod (whose
   real primary gateway is ``ai.openclaw.evo-gateway``) is detected as an orphan
   and removed through the Scheduler seam (``systemctl disable --now`` +
   delete-unit + ``daemon-reload``).
2. Negative control: a non-Evolve unit (sshd), the real primary gateway, and a
   live member-bot gateway are NOT removed (ownership gate + gateway keep-set).
3. A label owning multiple unit files (.service + .timer) is returned once and
   removed as a whole set.

⚠️ ``systemctl`` is never spawned for real — every test injects a
``SystemdScheduler`` with a recording runner and ``use_sudo=False`` so unit
files land in (and are deleted from) a tmp dir.
"""

from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

import pytest

_ADMIN_DIR = Path(__file__).resolve().parent.parent
_ANALYZER_DIR = _ADMIN_DIR.parent / "analyzer"
for _p in (str(_ADMIN_DIR), str(_ANALYZER_DIR)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from platform_profile import LINUX, set_profile  # noqa: E402

from evolve_admin import deploy  # noqa: E402
from evolve_admin.runtime import SystemdScheduler, set_scheduler  # noqa: E402
from runtime import scheduler as scheduler_mod  # noqa: E402


class _Runner:
    """Records argv lists; replies success to every systemctl call."""

    def __init__(self) -> None:
        self.calls: list[list[str]] = []

    def __call__(self, argv: list[str]) -> tuple[int, str, str]:
        self.calls.append([str(a) for a in argv])
        return (0, "", "")

    def verbs(self) -> list[str]:
        seen: list[str] = []
        for c in self.calls:
            for v in ("disable", "enable", "restart", "daemon-reload", "stop"):
                if any(a == v or str(a).endswith(f"/{v}") for a in c):
                    seen.append(v)
        return seen


@pytest.fixture(autouse=True)
def _forbid_real_scheduler_subprocess(monkeypatch):
    """A real subprocess from the scheduler module fails the test loudly —
    ``systemctl disable --now`` on a gateway is live-traffic destructive."""

    def _boom(*a, **kw):  # pragma: no cover — guard
        raise AssertionError(
            f"scheduler reached a REAL subprocess — inject a runner. argv={a!r}"
        )

    monkeypatch.setattr(scheduler_mod, "_subprocess_runner", _boom)
    yield
    set_scheduler(None)
    # The profile is owned by conftest's autouse _pin_macos_platform_profile
    # (it re-pins MACOS per test and on teardown); we only reset the scheduler.


def _pin_linux(unit_dir: Path, runner: _Runner) -> None:
    """Pin the LINUX profile with ``daemon_dir`` pointed at ``unit_dir`` and a
    SystemdScheduler writing/deleting in the same dir (use_sudo=False)."""
    set_profile(dataclasses.replace(LINUX, daemon_dir=str(unit_dir)))
    set_scheduler(SystemdScheduler(unit_dir=unit_dir, use_sudo=False, runner=runner))


def _write_unit(unit_dir: Path, name: str) -> Path:
    p = unit_dir / name
    p.write_text(
        "# Generated by Evolve (test fixture)\n[Unit]\nDescription=x\n"
        "[Service]\nExecStart=/bin/true\n"
    )
    return p


_EVO_PRIMARY_NET = {
    "networkId": "evo-pod",
    "primary": "evo",
    "members": [],
    "bots": {"evo": {"role": "primary", "user": "evo", "port": 19030}},
}


# ── 1. detect + remove the phantom gateway ───────────────────────────────────


def test_linux_detects_phantom_gateway_orphan(tmp_path):
    """The legacy ai.openclaw.evolve-gateway.service is an orphan on an
    evo-primary pod; the real ai.openclaw.evo-gateway is NOT."""
    runner = _Runner()
    _pin_linux(tmp_path, runner)
    net = dict(_EVO_PRIMARY_NET, sharedDir=str(tmp_path))

    phantom = _write_unit(tmp_path, "ai.openclaw.evolve-gateway.service")
    real_gw = _write_unit(tmp_path, "ai.openclaw.evo-gateway.service")
    real_infra = _write_unit(tmp_path, "ai.evolve.evolve.heal.service")

    orphans = deploy.find_orphaned_plists(net)

    assert orphans == [phantom], (
        f"expected only the phantom gateway, got {[p.name for p in orphans]}"
    )
    # The real primary gateway + a real infra daemon are spared on disk.
    assert real_gw.exists()
    assert real_infra.exists()


def test_linux_removes_phantom_gateway_through_seam(tmp_path):
    """remove_orphaned_plists drives SystemdScheduler.remove → disable --now +
    delete unit + daemon-reload, and the file is gone."""
    runner = _Runner()
    _pin_linux(tmp_path, runner)
    net = dict(_EVO_PRIMARY_NET, sharedDir=str(tmp_path))

    phantom = _write_unit(tmp_path, "ai.openclaw.evolve-gateway.service")
    real_gw = _write_unit(tmp_path, "ai.openclaw.evo-gateway.service")

    orphans = deploy.find_orphaned_plists(net)
    removed, failures = deploy.remove_orphaned_plists(orphans)

    assert removed == ["ai.openclaw.evolve-gateway"]
    assert failures == []
    assert not phantom.exists(), "phantom unit file should be deleted"
    assert real_gw.exists(), "the real primary gateway must be untouched"
    verbs = runner.verbs()
    assert "disable" in verbs, f"expected systemctl disable, got {verbs}"
    assert "daemon-reload" in verbs, f"expected daemon-reload, got {verbs}"


def test_linux_phantom_dry_run_issues_no_verbs(tmp_path):
    """dry_run reports the intent without disabling/deleting anything."""
    runner = _Runner()
    _pin_linux(tmp_path, runner)
    net = dict(_EVO_PRIMARY_NET, sharedDir=str(tmp_path))
    phantom = _write_unit(tmp_path, "ai.openclaw.evolve-gateway.service")

    orphans = deploy.find_orphaned_plists(net)
    removed, failures = deploy.remove_orphaned_plists(orphans, dry_run=True)

    assert removed == ["ai.openclaw.evolve-gateway"]
    assert failures == []
    assert runner.calls == [], "dry-run must not touch systemctl"
    assert phantom.exists(), "dry-run must not delete the unit"


# ── 2. negative control: never sweep real / non-Evolve units ─────────────────


def test_linux_spares_real_member_and_nonevolve_units(tmp_path):
    """A live member-bot gateway (keep-set widening), the real primary gateway,
    and non-Evolve units (sshd, nginx) are never flagged as orphans."""
    runner = _Runner()
    _pin_linux(tmp_path, runner)
    net = {
        "networkId": "evo-pod",
        "primary": "evo",
        "members": ["team-bot-a"],
        "bots": {
            "evo": {"role": "primary", "user": "evo", "port": 19030},
            "team-bot-a": {"role": "member", "user": "team-bot-a", "port": 19031},
        },
        "sharedDir": str(tmp_path),
    }

    real_primary = _write_unit(tmp_path, "ai.openclaw.evo-gateway.service")
    member_gw = _write_unit(tmp_path, "ai.openclaw.team-bot-a-gateway.service")
    sshd = _write_unit(tmp_path, "sshd.service")
    nginx = _write_unit(tmp_path, "nginx.service")

    orphans = deploy.find_orphaned_plists(net)

    assert orphans == [], (
        f"nothing should be orphaned, got {[p.name for p in orphans]}"
    )
    for p in (real_primary, member_gw, sshd, nginx):
        assert p.exists()


def test_linux_ownership_gate_excludes_nonevolve_even_when_unexpected(tmp_path):
    """A non-Evolve unit that is NOT in the keep-set is still excluded by the
    ownership gate — the sweep can never disable e.g. a hand-rolled operator
    unit just because Evolve doesn't know about it."""
    runner = _Runner()
    _pin_linux(tmp_path, runner)
    net = dict(_EVO_PRIMARY_NET, sharedDir=str(tmp_path))

    _write_unit(tmp_path, "operator-custom.service")
    _write_unit(tmp_path, "com.example.thing.service")
    _write_unit(tmp_path, "ai.openclaw.evo-gateway.service")  # the only real one

    orphans = deploy.find_orphaned_plists(net)
    assert orphans == []


def test_linux_legacy_evolve_primary_spares_evolve_gateway(tmp_path):
    """The symmetric risk to the phantom case: on a LEGACY evolve-primary pod
    (primary == "evolve") the real gateway IS ai.openclaw.evolve-gateway — it
    must be in the keep-set and NEVER swept."""
    runner = _Runner()
    _pin_linux(tmp_path, runner)
    net = {
        "networkId": "legacy-pod",
        "primary": "evolve",
        "members": [],
        "bots": {"evolve": {"role": "primary", "port": 19030}},
        "sharedDir": str(tmp_path),
    }
    real_gw = _write_unit(tmp_path, "ai.openclaw.evolve-gateway.service")

    orphans = deploy.find_orphaned_plists(net)
    assert orphans == [], (
        f"the real legacy gateway must be spared, got {[p.name for p in orphans]}"
    )
    assert real_gw.exists()


# ── 3. multi-unit label is returned once and removed as a set ────────────────


def test_linux_orphan_with_timer_returned_once_and_removed_whole(tmp_path):
    """A retired label owning .service + .timer is returned as ONE
    representative (the .service) and remove deletes the whole set."""
    runner = _Runner()
    _pin_linux(tmp_path, runner)
    net = dict(_EVO_PRIMARY_NET, sharedDir=str(tmp_path))
    _write_unit(tmp_path, "ai.openclaw.evo-gateway.service")  # keep

    svc = _write_unit(tmp_path, "ai.evolve.evolve.retired-job.service")
    tmr = _write_unit(tmp_path, "ai.evolve.evolve.retired-job.timer")

    orphans = deploy.find_orphaned_plists(net)
    assert orphans == [svc], (
        f"multi-unit label must dedup to one .service path, got "
        f"{[p.name for p in orphans]}"
    )

    removed, failures = deploy.remove_orphaned_plists(orphans)
    assert removed == ["ai.evolve.evolve.retired-job"]
    assert failures == []
    assert not svc.exists() and not tmr.exists(), (
        "SystemdScheduler.remove must delete the whole unit set"
    )


# ── 4. macOS path unchanged (no Linux scan leaks onto a mac pod) ─────────────


def test_macos_still_uses_launchd_glob(tmp_path, monkeypatch):
    """With the MACOS profile (default), find_orphaned_plists globs
    LAUNCHD_DIR for .plist files — the Linux systemd scan is not reached."""
    from platform_profile import MACOS

    set_profile(MACOS)
    monkeypatch.setattr(deploy, "LAUNCHD_DIR", tmp_path)
    net = dict(_EVO_PRIMARY_NET, sharedDir=str(tmp_path))

    orphan = tmp_path / "ai.evolve.evolve.stale-job.plist"
    orphan.write_text("<plist/>")
    # A systemd .service in the same dir must be ignored on macOS.
    (tmp_path / "ai.evolve.evolve.other.service").write_text("[Service]\n")

    orphans = deploy.find_orphaned_plists(net)
    assert orphans == [orphan]
