"""evolve_admin.channel_registry — the one declarative messaging-channel table.

Invariant 7 (docs/spec-users-meta-2026-06-15.md §5): *channel identity is
registry-driven, never a literal*. The set of messaging channels Evolve knows
about lives here and only here; every label / pairing rule / verify handler /
notify-priority table elsewhere in the codebase is a **projection** over this
table, selected by the CAPABILITY the consumer actually needs.

Why a sibling of ``channels.py`` and not part of it
---------------------------------------------------
``evolve_admin.channels`` answers a *runtime* question — "which channels does
this bot have enabled right now?" — by reading the bot's own ``openclaw.json``.
This module answers a *static* question — "what channels does Evolve know
about, and what can each one do?" Different lifetimes, different inputs, and
this one must stay import-light (no Flask, no subprocess, no filesystem) so
that ``web.routes_bot_users``, ``evo.tools.*``, and ``bot_templates.validator``
can all consume it without dragging each other's import graphs along. They are
neighbours, not one module.

THE CENTRAL DESIGN RULE — capability columns, not a flat list
--------------------------------------------------------------
This registry is **NOT** "the list of channels". Consumers are deliberately
narrower than each other, and flattening them would be a regression. Example:
name resolution is implemented for exactly three channels; a consumer that
asked this module for "all channels" would silently claim WhatsApp name
resolution and fail at runtime. So every consumer selects with a predicate:

    >>> ids_where(lambda c: c.supports_name_resolution)
    ('telegram', 'slack', 'discord')
    >>> ids_where(lambda c: c.verify_handler is not None)
    ('telegram', 'slack', 'discord', 'whatsapp', 'signal', 'imessage')

Adding a channel = adding one :class:`ChannelSpec` row with honest capability
flags. Every projection updates itself, and the flags that are ``False``/``None``
keep the narrow consumers narrow.

Sources of truth folded in here
--------------------------------
* ``install`` / ``oc_plugin_id`` — ``docs/skills/oc-channel-coverage.json``,
  the committed snapshot of OpenClaw's own channel catalog (regenerated by
  ``tools/list_oc_channels.py``). That file is the authority for what OC ships
  and how it installs; this table records only the subset Evolve's admin plane
  has opinions about, plus the two non-OC delivery ids (``email``,
  ``webhook``) that Evolve labels but does not provision.
* ``pairing`` — the ex-``pairing/config.py::_CHANNELS`` rows, moved here whole.
  ``pairing.config`` now re-exports its public API over this table.

Not in scope for this module
-----------------------------
The *shape* of a person's platform ids (``external_ids``) is M1-B2, not this
registry. This table describes channels, never users.
"""

from __future__ import annotations

import re
from typing import Callable, Iterable, Optional

# ── Pairing column ──────────────────────────────────────────────────────


class ChannelConfig:
    """Per-channel pairing UI + validation config — the ``pairing`` column.

    Moved verbatim from ``pairing/config.py`` (it was already the richest
    channel shape in the codebase; the registry reuses it rather than growing
    a parallel structure). ``pairing.config`` re-exports this name, so every
    existing importer keeps working.

    Attributes are read by both the Python backend (routes_pairing, install
    wizard) and serialized into the admin-UI bundle via ``to_ui_dict`` so the
    JS modal can render the right copy without forking the table.

      label              Channel name for prose ("Telegram", "Slack", …)
      id_label           UI label for the ID input field
      id_format_hint     Help text shown under the input
      id_validator       Regex (compiled) that a valid bare ID matches
      discovery_method   How the operator gets their ID/code:
                           "deeplink"  — Telegram, t.me/<bot>?start=…
                           "dm_bot"    — Slack/Discord/WhatsApp, send any DM
      deeplink_template  Format string with {bot_username}/{token} placeholders
                         (None for non-deeplink channels)
      open_button_label  Text on the "open the bot" button in the modal

    The "primary input" in the wizard is the *pairing code* the bot sent back
    to the operator, not the raw ID — codes are unique per pending request and
    let us auto-resolve identity (id + name + username) from the
    ``credentials/<channel>-pairing.json`` file. The id_validator is for the
    secondary "type your ID directly" path.

    OC stores pairing state per-bot at
    ``<bot_home>/.openclaw/credentials/<channel>-pairing.json`` (pending
    requests) and ``<channel>-default-allowFrom.json`` (approved IDs). See
    ``routes_bot_users`` for the read/write helpers we reuse.
    """

    __slots__ = (
        "channel",
        "label",
        "id_label",
        "id_format_hint",
        "_id_validator_pattern",
        "_id_validator",
        "discovery_method",
        "deeplink_template",
        "open_button_label",
    )

    def __init__(
        self,
        channel: str,
        label: str,
        id_label: str,
        id_format_hint: str,
        id_validator_pattern: str,
        discovery_method: str,
        deeplink_template: Optional[str],
        open_button_label: str,
    ) -> None:
        if discovery_method not in ("deeplink", "dm_bot"):
            raise ValueError(
                f"unknown discovery_method {discovery_method!r} for {channel}"
            )
        if discovery_method == "deeplink" and not deeplink_template:
            raise ValueError(
                f"discovery_method=deeplink requires deeplink_template ({channel})"
            )
        self.channel = channel
        self.label = label
        self.id_label = id_label
        self.id_format_hint = id_format_hint
        self._id_validator_pattern = id_validator_pattern
        self._id_validator = re.compile(id_validator_pattern)
        self.discovery_method = discovery_method
        self.deeplink_template = deeplink_template
        self.open_button_label = open_button_label

    def validate_id(self, value: str) -> bool:
        """Cheap format check for the "type your ID directly" path.

        Returns True iff ``value`` matches the channel's ID format.
        This catches typos and obvious copy/paste mistakes; it does
        NOT verify the ID actually exists on the channel side — that
        happens implicitly when the bot's gateway sees a real DM from
        that ID and writes the pairing request.
        """
        if not isinstance(value, str):
            return False
        return bool(self._id_validator.fullmatch(value.strip()))

    def deeplink_for(
        self,
        bot_username: Optional[str],
        token: Optional[str] = None,
    ) -> Optional[str]:
        """Build the per-channel "open bot DM" URL, or None.

        For Telegram, returns ``https://t.me/<bot_username>?start=<token>``
        — the deeplink opens the bot conversation in Telegram desktop
        or mobile with one tap. The ``start`` param is decorative
        (OC's gateway doesn't capture it into pairing meta — verified
        2026-06-01 in dist/bot-iSDqdz0Y.js:1380), but harmless and
        useful for telemetry.

        For Slack/Discord/WhatsApp, returns None — those platforms
        either don't support deeplinks (Slack) or the UX is just
        "search for the bot by name." The modal renders a copyable
        bot-handle string in those cases.
        """
        if not self.deeplink_template:
            return None
        if not bot_username:
            return None
        # Template uses str.format placeholders; missing token is OK
        # (renders as empty string after stripping).
        rendered = self.deeplink_template.format(
            bot_username=bot_username.lstrip("@"),
            token=token or "",
        )
        # If the token slot was empty, strip the trailing query param
        # so the URL stays clean.
        if rendered.endswith("?start="):
            rendered = rendered[: -len("?start=")]
        return rendered

    def to_ui_dict(self) -> dict:
        """Serializable shape for the admin-UI bundle.

        The JS modal reads these fields verbatim — keep the keys in
        sync with ``index.html``'s ``_PAIR_CFG`` consumer.
        """
        return {
            "channel": self.channel,
            "label": self.label,
            "id_label": self.id_label,
            "id_format_hint": self.id_format_hint,
            "id_validator_pattern": self._id_validator_pattern,
            "discovery_method": self.discovery_method,
            "has_deeplink": bool(self.deeplink_template),
            "open_button_label": self.open_button_label,
        }


# ── Install classes ─────────────────────────────────────────────────────

# How a channel reaches a bot's OpenClaw install. Values mirror
# docs/skills/oc-channel-coverage.json::default_install:
#   "core"            — bundled with OC (default_install: "bundled"); nothing
#                       to npm-install, just enable the channels.<id> block.
#   "official-plugin" — @openclaw/* published to npm or clawhub
#                       (default_install: "npm" | "clawhub").
#   "external-plugin" — third-party namespace (reserved; no row uses it yet).
#   None              — not an OC channel at all (email / webhook are delivery
#                       mechanisms Evolve labels but never provisions).
INSTALL_CORE = "core"
INSTALL_OFFICIAL_PLUGIN = "official-plugin"
INSTALL_EXTERNAL_PLUGIN = "external-plugin"

_VALID_INSTALLS = frozenset({
    INSTALL_CORE, INSTALL_OFFICIAL_PLUGIN, INSTALL_EXTERNAL_PLUGIN, None,
})


class ChannelSpec:
    """One row of the registry — a channel and everything Evolve knows it can do.

    Every field is a CAPABILITY a consumer selects on. A field that is
    ``None``/``False`` is a load-bearing statement ("Evolve cannot do this for
    this channel"), not a TODO — that is what keeps narrow consumers narrow.
    """

    __slots__ = (
        "id",
        "display_label",
        "_prose_label",
        "pairing",
        "verify_handler",
        "notify_priority",
        "supports_name_resolution",
        "install",
        "oc_plugin_id",
        "supports_dms",
        "supports_groups",
        "supports_allowlist",
        "messaging_integration",
    )

    def __init__(
        self,
        id: str,
        display_label: str,
        *,
        prose_label: Optional[str] = None,
        pairing: Optional[ChannelConfig] = None,
        verify_handler: Optional[str] = None,
        notify_priority: Optional[int] = None,
        supports_name_resolution: bool = False,
        install: Optional[str] = None,
        oc_plugin_id: Optional[str] = None,
        supports_dms: bool = False,
        supports_groups: bool = False,
        supports_allowlist: bool = False,
        messaging_integration: bool = False,
    ) -> None:
        if install not in _VALID_INSTALLS:
            raise ValueError(f"unknown install class {install!r} for {id}")
        if pairing is not None and pairing.channel != id:
            raise ValueError(
                f"pairing config channel {pairing.channel!r} != row id {id!r}"
            )
        if install is None and oc_plugin_id is not None:
            raise ValueError(
                f"{id}: oc_plugin_id set but install is None (not an OC channel)"
            )
        self.id = id
        self.display_label = display_label
        self._prose_label = prose_label
        self.pairing = pairing
        self.verify_handler = verify_handler
        self.notify_priority = notify_priority
        self.supports_name_resolution = supports_name_resolution
        self.install = install
        self.oc_plugin_id = oc_plugin_id
        self.supports_dms = supports_dms
        self.supports_groups = supports_groups
        self.supports_allowlist = supports_allowlist
        self.messaging_integration = messaging_integration

    @property
    def prose_label(self) -> str:
        """Label for mid-sentence prose ("…messages you on Telegram", "…via
        email"). Defaults to ``display_label``; overridden only where the
        product name is not a proper noun (email) or needs an article
        (a configured webhook)."""
        return self._prose_label if self._prose_label is not None else self.display_label

    @property
    def supports_pairing(self) -> bool:
        """True iff Evolve can run its ID-pairing flow on this channel."""
        return self.pairing is not None

    def __repr__(self) -> str:  # pragma: no cover - debug aid
        return f"<ChannelSpec {self.id}>"


# ── The registry ────────────────────────────────────────────────────────

# Order is the canonical display order. Telegram first (dominant channel),
# then the rest of the paired channels, then verify-only channels, then the
# label-only delivery ids. `notify_priority` is an explicit int rather than
# list position because the notify order (telegram → signal → whatsapp →
# slack → discord) is deliberately NOT the display order.
_REGISTRY: tuple[ChannelSpec, ...] = (
    ChannelSpec(
        id="telegram",
        display_label="Telegram",
        pairing=ChannelConfig(
            channel="telegram",
            label="Telegram",
            id_label="Telegram user ID",
            id_format_hint=(
                "6-12 digit number. If you don't know yours, DM the bot "
                "and paste the code it replies with."
            ),
            # Telegram user IDs are 32-bit ints today but the API will
            # widen to 64-bit per Telegram's roadmap. We bound 6-12 to
            # cover both eras without admitting unrelated numeric noise.
            id_validator_pattern=r"^\d{6,12}$",
            discovery_method="deeplink",
            # The ``start`` query param IS captured by Telegram and
            # delivered as ``/start <param>`` in the bot's first message,
            # but OC's enforceTelegramDmAccess (bot-iSDqdz0Y.js:1380)
            # only reads msg.from.{id,username,first_name,last_name} into
            # pairing meta — the text body is dropped. So the token is
            # decorative for one-tap opening; identity still resolves via
            # the pairing code the operator pastes back.
            deeplink_template="https://t.me/{bot_username}?start={token}",
            open_button_label="Open in Telegram",
        ),
        verify_handler="_check_telegram_token",
        notify_priority=1,
        supports_name_resolution=True,
        install=INSTALL_CORE,
        oc_plugin_id="@openclaw/telegram",
        supports_dms=True,
        supports_groups=True,
        supports_allowlist=True,
        messaging_integration=True,
    ),
    ChannelSpec(
        id="slack",
        display_label="Slack",
        pairing=ChannelConfig(
            channel="slack",
            label="Slack",
            id_label="Slack member ID",
            id_format_hint=(
                "Starts with U (e.g. U01ABCDE2FG). Find it in your "
                "Slack profile → ⋮ menu → Copy member ID."
            ),
            # Slack member IDs are U or W (workspace-bot edge case) +
            # uppercase alphanumeric; 9-11 chars in practice.
            id_validator_pattern=r"^[UW][A-Z0-9]{8,10}$",
            discovery_method="dm_bot",
            deeplink_template=None,
            open_button_label="Copy bot handle",
        ),
        verify_handler="_check_slack_token",
        notify_priority=4,
        supports_name_resolution=True,
        install=INSTALL_OFFICIAL_PLUGIN,
        oc_plugin_id="@openclaw/slack",
        supports_dms=True,
        supports_groups=True,
        supports_allowlist=True,
        messaging_integration=True,
    ),
    ChannelSpec(
        id="discord",
        display_label="Discord",
        pairing=ChannelConfig(
            channel="discord",
            label="Discord",
            id_label="Discord user ID",
            id_format_hint=(
                "17-19 digit snowflake. Enable Developer Mode in "
                "Settings → Advanced, then right-click yourself → Copy User ID."
            ),
            # Discord snowflake IDs are 17-19 digits (and growing — the
            # range will keep shifting upward as Discord's epoch advances).
            id_validator_pattern=r"^\d{17,19}$",
            discovery_method="dm_bot",
            deeplink_template=None,
            open_button_label="Copy bot handle",
        ),
        verify_handler="_check_discord_token",
        notify_priority=5,
        supports_name_resolution=True,
        install=INSTALL_OFFICIAL_PLUGIN,
        oc_plugin_id="@openclaw/discord",
        supports_dms=True,
        supports_groups=True,
        supports_allowlist=True,
        messaging_integration=True,
    ),
    ChannelSpec(
        id="whatsapp",
        display_label="WhatsApp",
        pairing=ChannelConfig(
            channel="whatsapp",
            label="WhatsApp",
            id_label="WhatsApp phone number",
            id_format_hint=(
                "E.164 format with country code, e.g. +14155551234. "
                "It's your own phone number — no need to look anything up."
            ),
            # E.164 caps phone numbers at 15 digits; we floor at 10 to
            # admit US-style numbers without the leading 1.
            id_validator_pattern=r"^\+\d{10,15}$",
            discovery_method="dm_bot",
            deeplink_template=None,
            open_button_label="Copy bot handle",
        ),
        verify_handler="_check_whatsapp_local",
        notify_priority=3,
        # No name resolution: OC's WhatsApp channel exposes phone numbers,
        # not a directory API. Claiming support here would make
        # name_resolver fail silently on WhatsApp.
        supports_name_resolution=False,
        install=INSTALL_OFFICIAL_PLUGIN,
        oc_plugin_id="@openclaw/whatsapp",
        supports_dms=True,
        supports_groups=True,
        supports_allowlist=True,
        messaging_integration=True,
    ),
    ChannelSpec(
        id="signal",
        display_label="Signal",
        # No pairing row: routes_bot_users has deliberately hidden Signal
        # from the Users UI since 2026-05-29 (an empty-state placeholder
        # confused operators). Give it a ChannelConfig when a real Signal
        # pairing integration lands.
        pairing=None,
        verify_handler="_check_signal_local",
        notify_priority=2,
        supports_name_resolution=False,
        install=INSTALL_CORE,
        oc_plugin_id="@openclaw/signal",
        supports_dms=True,
        supports_groups=True,
        supports_allowlist=True,
        messaging_integration=True,
    ),
    ChannelSpec(
        id="imessage",
        display_label="iMessage",
        pairing=None,
        verify_handler="_check_imessage_local",
        # No notify priority: the alert/OOO dispatch path has no iMessage
        # sender. Listing it would route operator alerts into a black hole.
        notify_priority=None,
        supports_name_resolution=False,
        install=INSTALL_CORE,
        oc_plugin_id="@openclaw/imessage",
        supports_dms=True,
        supports_groups=True,
        supports_allowlist=True,
        messaging_integration=True,
    ),
    ChannelSpec(
        id="sms",
        display_label="SMS",
        pairing=None,
        verify_handler=None,
        notify_priority=None,
        supports_name_resolution=False,
        install=INSTALL_CORE,
        oc_plugin_id="@openclaw/sms",
        supports_dms=True,
        supports_groups=False,
        supports_allowlist=False,
        messaging_integration=True,
    ),
    ChannelSpec(
        id="email",
        display_label="Email",
        # Lowercase mid-sentence: "email" is not a proper noun, and the
        # safety summary reads "…emails you" / "…on email".
        prose_label="email",
        pairing=None,
        verify_handler=None,
        notify_priority=None,
        supports_name_resolution=False,
        # Not an OpenClaw channel — a delivery mechanism Evolve labels in
        # safety summaries and accepts as a bot-template target.
        install=None,
        oc_plugin_id=None,
        supports_dms=True,
        supports_groups=False,
        supports_allowlist=False,
        messaging_integration=True,
    ),
    ChannelSpec(
        id="webhook",
        display_label="Webhook",
        prose_label="a configured webhook",
        pairing=None,
        verify_handler=None,
        notify_priority=None,
        supports_name_resolution=False,
        install=None,
        oc_plugin_id=None,
        supports_dms=False,
        supports_groups=False,
        supports_allowlist=False,
        # Deliberately False: a webhook is a delivery sink, not a messaging
        # channel a person is reachable on. The C-A4 coherence gate must not
        # accept a webhook as satisfying a messaging-integration requirement.
        messaging_integration=False,
    ),
)

_BY_ID: dict[str, ChannelSpec] = {c.id: c for c in _REGISTRY}


# ── Selection API ───────────────────────────────────────────────────────


def all_channels() -> tuple[ChannelSpec, ...]:
    """Every registry row, in canonical display order."""
    return _REGISTRY


def get(channel_id: str) -> Optional[ChannelSpec]:
    """Look up one row by id (case-insensitive), or None if unknown."""
    if not isinstance(channel_id, str):
        return None
    return _BY_ID.get(channel_id.strip().lower())


def where(predicate: Callable[[ChannelSpec], bool]) -> tuple[ChannelSpec, ...]:
    """Rows matching ``predicate``, in canonical display order.

    This is the ONLY sanctioned way for a consumer to narrow the registry.
    Never copy a subset of ids into your module — declare the capability you
    need and filter on it, so a new channel row updates you for free and an
    unsupported one keeps you honest.
    """
    return tuple(c for c in _REGISTRY if predicate(c))


def ids_where(predicate: Callable[[ChannelSpec], bool]) -> tuple[str, ...]:
    """Channel ids matching ``predicate``, in canonical display order."""
    return tuple(c.id for c in where(predicate))


def labels_where(
    predicate: Callable[[ChannelSpec], bool],
    *,
    prose: bool = False,
) -> dict[str, str]:
    """``{id: label}`` for rows matching ``predicate``.

    ``prose=True`` selects :attr:`ChannelSpec.prose_label` (mid-sentence
    form) instead of the product-name ``display_label``.
    """
    return {
        c.id: (c.prose_label if prose else c.display_label)
        for c in where(predicate)
    }


def by_notify_priority() -> tuple[str, ...]:
    """Channel ids that Evolve can SEND to, in notify-fallback order.

    Backs both ``breakers_enforce._USER_CHANNEL_PRIORITY`` (per-bot OOO
    posting) and ``alerts.dispatcher._DEFAULT_CHANNEL_PRIORITY`` (operator
    alerts). Those two tables were byte-identical by coincidence; deriving
    both from ``notify_priority`` makes it structural.
    """
    ranked = [c for c in _REGISTRY if c.notify_priority is not None]
    ranked.sort(key=lambda c: c.notify_priority)  # type: ignore[arg-type,return-value]
    return tuple(c.id for c in ranked)


def pairing_channels() -> tuple[ChannelSpec, ...]:
    """Rows with a pairing config — the channels the Users UI surfaces."""
    return where(lambda c: c.supports_pairing)


def pairing_channel_ids() -> tuple[str, ...]:
    """Ids of the pairing-capable channels, in display order."""
    return ids_where(lambda c: c.supports_pairing)


def name_resolution_channels() -> frozenset[str]:
    """Channels with a working name-resolution adapter.

    Narrow ON PURPOSE — this is the canonical example of why the registry
    has capability columns. Widening it to "all channels" would make
    ``evo.name_resolver`` claim support it does not have.
    """
    return frozenset(ids_where(lambda c: c.supports_name_resolution))


def verify_handlers() -> dict[str, str]:
    """``{channel_id: wizard_verify handler name}`` for verifiable channels."""
    return {
        c.id: c.verify_handler
        for c in _REGISTRY
        if c.verify_handler is not None
    }


def messaging_integration_ids() -> frozenset[str]:
    """Channel ids that count as "messaging-capable" for the app coherence
    gate. Excludes ``webhook`` (a delivery sink, not a channel)."""
    return frozenset(ids_where(lambda c: c.messaging_integration))


def known_ids() -> frozenset[str]:
    """Every id in the registry. Use a narrower selector unless you genuinely
    mean "any channel Evolve has heard of"."""
    return frozenset(_BY_ID)


def display_label(channel_id: str, *, prose: bool = False) -> str:
    """Operator-facing name for a channel id, with a title-case fallback so an
    unregistered id still reads like a product name."""
    spec = get(channel_id)
    if spec is not None:
        return spec.prose_label if prose else spec.display_label
    cid = (channel_id or "").strip()
    return cid.title()


def iter_ids(specs: Iterable[ChannelSpec]) -> tuple[str, ...]:
    """Small helper: ids out of a row iterable, order preserved."""
    return tuple(c.id for c in specs)
