"""
evolve_admin/tunnel.py — SSH tunnel helpers for laptop-side setup.

Two surfaces share this module:

1. **Admin-UI .command-file generation.** The Admin UI runs on the Mac Mini
   and cannot execute commands on the user's laptop. It offers downloadable
   .command files (macOS shell scripts that double-click-open in Terminal)
   so a non-technical operator can run the install with no special tools.
   See ``generate_setup_command`` / ``generate_connect_command``.

2. **In-process laptop-side install/uninstall.** Operators who already have
   ``evolve-admin`` on the laptop can skip the .command file detour and just
   run ``evolve-admin connect``. The functions ``install_persistent_tunnel``,
   ``uninstall_persistent_tunnel``, ``tunnel_status`` and
   ``run_one_shot_tunnel`` are the building blocks for that CLI surface.

Both surfaces produce the same launchd agent (label ``com.evolve.tunnel``),
so an operator can install via either path and manage it via the other.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path
from typing import TypedDict

from .runtime import JobSpec, LaunchdScheduler, render_launchd_plist

TUNNEL_LABEL = "com.evolve.tunnel"

# raw()-debt exemption (S2): the tunnel agent is a USER-SESSION LaunchAgent
# managed wherever `evolve-admin tunnel` runs (often the operator's own Mac),
# via unsudo'd legacy `launchctl load/unload/list` in the gui session. The
# Scheduler verbs are system-domain + sudo'd (install() also owns the plist
# write); forcing them here would change domain, privilege, and ownership
# semantics. raw() keeps the exact argv on the injectable runner.
_agent_launchctl = LaunchdScheduler(use_sudo=False)


def _plist_path() -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{TUNNEL_LABEL}.plist"


def _log_path() -> Path:
    return Path.home() / ".evolve" / "logs" / "tunnel.log"


class TunnelConfig(TypedDict, total=False):
    remote_host: str    # SSH hostname/alias for the Mac Mini (e.g. "mini" or "192.168.1.10")
    remote_user: str    # SSH username on the mini (the human admin's macOS account)
    remote_port: int    # Port the admin server listens on (default 5050)
    local_port: int     # Local port to forward to (default 5050)
    ssh_key: str        # Path to SSH private key on laptop (default "~/.ssh/id_ed25519")


# NOTE (plist-emitter exemption): the bash script below builds its launchd
# plist via a heredoc AT RUN TIME on the *operator's laptop* (autossh
# detection, SSH args are runtime bash variables there), so it structurally
# cannot route through evolve_admin.runtime.render_launchd_plist — the
# laptop doesn't have evolve installed. This is the one sanctioned
# hand-rolled plist outside the JobSpec renderer; everything that renders
# on the pod host goes through JobSpec (see runtime/scheduler.py).
#
# NOTE (Scheduler-seam exemption, 4.3c S2): the in-process ``launchctl
# load``/``unload``/``list`` calls in this module are likewise sanctioned
# debt OFF the Scheduler seam. They run on the operator's laptop (a Mac
# by definition for this LaunchAgent surface), not on the pod host the
# Linux-port seam abstracts — and the process-wide ``get_scheduler()``
# singleton is the *pod-host* adapter (sudo-prefixed, system domain),
# the wrong instance for an unsudo'd user-domain agent on the client.
# If the laptop surface ever grows a non-macOS variant it gets its own
# client-side abstraction, not the pod scheduler.
_SETUP_COMMAND = '''\
#!/bin/bash
# ================================================================
# Evolve Tunnel Setup
# Generated by Evolve Admin UI
#
# Run this script ONCE on your laptop to install a persistent SSH
# tunnel to the Evolve Admin UI on your Mac Mini.
#
# Double-click this file in Finder, or run:
#   bash evolve-tunnel-setup.command
# ================================================================

set -e

REMOTE_HOST="{remote_host}"
REMOTE_USER="{remote_user}"
REMOTE_PORT="{remote_port}"
LOCAL_PORT="{local_port}"
SSH_KEY_RAW="{ssh_key}"
SSH_KEY="${{SSH_KEY_RAW/\\~/$HOME}}"
LABEL="com.evolve.tunnel"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LOG="$HOME/.evolve/logs/tunnel.log"

echo ""
echo "=== Evolve Tunnel Setup ==="
echo ""

mkdir -p "$HOME/.evolve/logs"
mkdir -p "$HOME/Library/LaunchAgents"

# ── Port conflict check ──────────────────────────────────────────
if lsof -i ":$LOCAL_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
  echo "WARNING: Port $LOCAL_PORT is already in use on this machine."
  echo "         Another tunnel or service may be running."
  echo "         You may need to stop it first, or choose a different port."
  echo ""
fi

# ── SSH key check ────────────────────────────────────────────────
if [ ! -f "$SSH_KEY" ]; then
  echo "NOTE: SSH key not found at $SSH_KEY"
  echo "      The tunnel launchd agent needs passwordless SSH to reconnect"
  echo "      automatically. Set up SSH key auth with:"
  echo ""
  echo "        ssh-keygen -t ed25519"
  echo "        ssh-copy-id -i $SSH_KEY $REMOTE_USER@$REMOTE_HOST"
  echo ""
  echo "      Continuing anyway — you may be prompted for a password each reconnect."
  echo ""
  SSH_KEY_FLAG=""
else
  SSH_KEY_FLAG="-i \\"$SSH_KEY\\""
fi

# ── Find tunnel binary (prefer autossh) ──────────────────────────
AUTOSSH_BIN=""
if command -v autossh >/dev/null 2>&1; then
  AUTOSSH_BIN="$(which autossh)"
elif command -v brew >/dev/null 2>&1; then
  echo "Installing autossh via Homebrew (recommended for reliable auto-reconnect)..."
  brew install autossh
  AUTOSSH_BIN="$(which autossh)"
fi

if [ -n "$AUTOSSH_BIN" ]; then
  TUNNEL_BIN="$AUTOSSH_BIN"
  TUNNEL_EXTRA="-M 0"
  echo "✓ Using autossh for reliable auto-reconnect"
else
  TUNNEL_BIN="/usr/bin/ssh"
  TUNNEL_EXTRA=""
  echo "  Using ssh (install autossh via Homebrew for better reliability)"
fi

# ── Write launchd plist ──────────────────────────────────────────
# Build ProgramArguments array items
build_plist_args() {{
  local item
  for item in "$@"; do
    printf '        <string>%s</string>\\n' "$item"
  done
}}

SSH_ARGS=($SSH_KEY_FLAG -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -N -L "$LOCAL_PORT:localhost:$REMOTE_PORT" "$REMOTE_USER@$REMOTE_HOST")

{{
cat << PLIST_HEADER
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$TUNNEL_BIN</string>
PLIST_HEADER

if [ -n "$TUNNEL_EXTRA" ]; then
  for word in $TUNNEL_EXTRA; do
    printf '        <string>%s</string>\\n' "$word"
  done
fi

for arg in "${{SSH_ARGS[@]}}"; do
  printf '        <string>%s</string>\\n' "$arg"
done

cat << PLIST_FOOTER
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$LOG</string>
    <key>StandardErrorPath</key>
    <string>$LOG</string>
</dict>
</plist>
PLIST_FOOTER
}} > "$PLIST"

echo "✓ Plist written to $PLIST"

# ── Load agent ───────────────────────────────────────────────────
if launchctl list 2>/dev/null | grep -q "$LABEL"; then
  echo "  Reloading existing tunnel agent..."
  launchctl unload "$PLIST" 2>/dev/null || true
fi

launchctl load "$PLIST"
echo "✓ Tunnel agent loaded and running"

echo ""
echo "================================================================"
echo "  Setup complete!"
echo ""
echo "  The tunnel will reconnect automatically when your laptop"
echo "  reboots or the connection drops."
echo ""
echo "  Open your browser to: http://localhost:$LOCAL_PORT"
echo "================================================================"
echo ""
echo "Press any key to close this window."
read -n 1
'''

_CONNECT_COMMAND = '''\
#!/bin/bash
# ================================================================
# Evolve Tunnel — one-shot connect
# Generated by Evolve Admin UI
#
# Keep this on your desktop as a manual reconnect backup.
# Double-click to open the tunnel for the current session.
# (For persistent tunneling, run evolve-tunnel-setup.command instead.)
# ================================================================

REMOTE_HOST="{remote_host}"
REMOTE_USER="{remote_user}"
REMOTE_PORT="{remote_port}"
LOCAL_PORT="{local_port}"
SSH_KEY_RAW="{ssh_key}"
SSH_KEY="${{SSH_KEY_RAW/\\~/$HOME}}"

SSH_KEY_OPT=""
if [ -f "$SSH_KEY" ]; then
  SSH_KEY_OPT="-i \\"$SSH_KEY\\""
fi

echo "Connecting to Evolve Admin UI..."
echo "  Tunnel: localhost:$LOCAL_PORT → $REMOTE_USER@$REMOTE_HOST:$REMOTE_PORT"
echo ""
echo "Leave this window open. Close it to disconnect."
echo "  Press Ctrl+C to stop the tunnel."
echo ""

exec ssh $SSH_KEY_OPT \\
    -o ServerAliveInterval=30 \\
    -o ServerAliveCountMax=3 \\
    -o ExitOnForwardFailure=yes \\
    -N \\
    -L "$LOCAL_PORT:localhost:$REMOTE_PORT" \\
    "$REMOTE_USER@$REMOTE_HOST"
'''


def _autodetect_remote_host() -> str:
    """Pull the deploy box's hostname from network.json's adminBaseUrl.

    Used as a default when the operator submits the tunnel form without
    filling in a remote_host. Falls back to ``""`` (which makes the
    generated script fail-loud rather than silently dialing the wrong
    box) when network.json is unreachable or the URL can't be parsed.
    """
    try:
        from .config import load_network, DEFAULT_NETWORK_CONFIG
        net = load_network(DEFAULT_NETWORK_CONFIG)
        admin_url = net.get("adminBaseUrl") or ""
        if isinstance(admin_url, str) and admin_url:
            import re
            m = re.match(r"https?://([^/:]+)", admin_url)
            if m:
                return m.group(1)
    except Exception:
        pass
    return ""


def _autodetect_remote_user() -> str:
    """Pull the admin username from network.json's admin_user field."""
    try:
        from .config import load_network, DEFAULT_NETWORK_CONFIG
        return str(load_network(DEFAULT_NETWORK_CONFIG).get("admin_user") or "")
    except Exception:
        return ""


def generate_setup_command(cfg: TunnelConfig) -> str:
    """Generate the evolve-tunnel-setup.command shell script content."""
    return _SETUP_COMMAND.format(
        remote_host=cfg.get("remote_host") or _autodetect_remote_host(),
        remote_user=cfg.get("remote_user") or _autodetect_remote_user(),
        remote_port=cfg.get("remote_port", 5050),
        local_port=cfg.get("local_port", 5050),
        ssh_key=cfg.get("ssh_key", "~/.ssh/id_ed25519"),
    )


def generate_connect_command(cfg: TunnelConfig) -> str:
    """Generate the evolve-tunnel-connect.command shell script content."""
    return _CONNECT_COMMAND.format(
        remote_host=cfg.get("remote_host") or _autodetect_remote_host(),
        remote_user=cfg.get("remote_user") or _autodetect_remote_user(),
        remote_port=cfg.get("remote_port", 5050),
        local_port=cfg.get("local_port", 5050),
        ssh_key=cfg.get("ssh_key", "~/.ssh/id_ed25519"),
    )


# ── In-process laptop-side install/uninstall/status ─────────────────────────


def _resolve_ssh_key(ssh_key: str) -> Path:
    return Path(os.path.expanduser(ssh_key))


def _ssh_args(
    remote_host: str,
    remote_user: str,
    remote_port: int,
    local_port: int,
    ssh_key: Path | None,
) -> list[str]:
    args: list[str] = []
    if ssh_key and ssh_key.exists():
        args += ["-i", str(ssh_key)]
    args += [
        "-o", "ServerAliveInterval=30",
        "-o", "ServerAliveCountMax=3",
        "-o", "ExitOnForwardFailure=yes",
        "-N",
        "-L", f"{local_port}:localhost:{remote_port}",
    ]
    target = f"{remote_user}@{remote_host}" if remote_user else remote_host
    args.append(target)
    return args


def _autossh_path() -> str | None:
    """Return path to autossh if installed, else None."""
    return shutil.which("autossh")


def _build_plist_xml(
    program: str,
    program_args: list[str],
    log_path: Path,
    keep_alive: bool = True,
) -> str:
    """Render the tunnel LaunchAgent plist (pure — no disk access).

    ``keep_alive=False`` omits the KeepAlive key (launchd's default is
    false) — the old hand-rolled emitter wrote an explicit <false/>;
    behaviorally identical, and no caller passes False today.
    """
    return render_launchd_plist(JobSpec(
        label=TUNNEL_LABEL,
        program_args=[program, *program_args],
        run_at_load=True,
        keep_alive=keep_alive,
        stdout_path=str(log_path),
        stderr_path=str(log_path),
    ))


def install_persistent_tunnel(cfg: TunnelConfig) -> dict:
    """Install (or reinstall) the persistent SSH tunnel launchd agent.

    Idempotent: if the agent is already loaded, it is reloaded with the new
    plist. Prefers autossh when present (reliable auto-reconnect on flap),
    falls back to plain /usr/bin/ssh otherwise.

    Returns a dict with keys: plist_path, log_path, used_autossh, label.
    """
    remote_host = cfg.get("remote_host") or _autodetect_remote_host()
    remote_user = cfg.get("remote_user") or _autodetect_remote_user()
    remote_port = int(cfg.get("remote_port", 5050))
    local_port = int(cfg.get("local_port", 5050))
    ssh_key = _resolve_ssh_key(cfg.get("ssh_key", "~/.ssh/id_ed25519"))

    if not remote_host:
        raise RuntimeError(
            "remote_host is required — pass --host or set adminBaseUrl in network.json"
        )

    plist = _plist_path()
    log = _log_path()
    log.parent.mkdir(parents=True, exist_ok=True)
    plist.parent.mkdir(parents=True, exist_ok=True)

    autossh = _autossh_path()
    if autossh:
        program = autossh
        program_args = ["-M", "0", *_ssh_args(remote_host, remote_user, remote_port, local_port, ssh_key)]
    else:
        program = "/usr/bin/ssh"
        program_args = _ssh_args(remote_host, remote_user, remote_port, local_port, ssh_key)

    plist.write_text(_build_plist_xml(program, program_args, log))

    # Reload if already loaded (gui-session legacy verbs — see module note)
    _rc, listed_out, _err = _agent_launchctl.raw("list")
    if TUNNEL_LABEL in listed_out:
        _agent_launchctl.raw("unload", str(plist))

    load_rc, _out, load_err = _agent_launchctl.raw("load", str(plist))
    if load_rc != 0:
        raise RuntimeError(f"launchctl load failed: {load_err.strip()}")

    return {
        "plist_path": str(plist),
        "log_path": str(log),
        "used_autossh": bool(autossh),
        "label": TUNNEL_LABEL,
        "remote_host": remote_host,
        "remote_user": remote_user,
        "remote_port": remote_port,
        "local_port": local_port,
        "ssh_key_present": ssh_key.exists(),
    }


def uninstall_persistent_tunnel() -> dict:
    """Stop and remove the persistent tunnel launchd agent.

    Returns {"removed": bool, "plist_path": str}. Safe to call when nothing
    is installed — returns removed=False.
    """
    plist = _plist_path()
    if not plist.exists():
        return {"removed": False, "plist_path": str(plist)}

    _agent_launchctl.raw("unload", str(plist))
    plist.unlink()
    return {"removed": True, "plist_path": str(plist)}


def tunnel_status(local_port: int = 5050) -> dict:
    """Inspect the tunnel agent and port to decide if it's actually up.

    Returns a dict with keys:
      installed (bool)            — plist file exists
      loaded (bool)               — launchctl knows about the label
      pid (int | None)            — process id if running
      listening_on_local (bool)   — something is on local_port
      plist_path (str)
      log_path (str)
    """
    plist = _plist_path()
    info: dict = {
        "installed": plist.exists(),
        "loaded": False,
        "pid": None,
        "listening_on_local": False,
        "plist_path": str(plist),
        "log_path": str(_log_path()),
    }

    _rc, listed_out, _err = _agent_launchctl.raw("list")
    for line in listed_out.splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[-1] == TUNNEL_LABEL:
            info["loaded"] = True
            try:
                info["pid"] = int(parts[0]) if parts[0] != "-" else None
            except ValueError:
                info["pid"] = None
            break

    lsof = subprocess.run(
        ["lsof", "-iTCP", f"-i:{local_port}", "-sTCP:LISTEN", "-P", "-n"],
        capture_output=True, text=True,
    )
    info["listening_on_local"] = bool(lsof.stdout.strip())
    return info


def run_one_shot_tunnel(cfg: TunnelConfig) -> int:
    """Exec a foreground ssh tunnel; blocks until Ctrl+C or remote drop.

    Returns the ssh exit code. Does not install or touch launchd.
    """
    remote_host = cfg.get("remote_host") or _autodetect_remote_host()
    remote_user = cfg.get("remote_user") or _autodetect_remote_user()
    remote_port = int(cfg.get("remote_port", 5050))
    local_port = int(cfg.get("local_port", 5050))
    ssh_key = _resolve_ssh_key(cfg.get("ssh_key", "~/.ssh/id_ed25519"))

    if not remote_host:
        raise RuntimeError(
            "remote_host is required — pass --host or set adminBaseUrl in network.json"
        )

    cmd = ["/usr/bin/ssh", *_ssh_args(remote_host, remote_user, remote_port, local_port, ssh_key)]
    return subprocess.call(cmd)


def browser_shortcut_instructions(local_port: int = 5050) -> dict:
    """Return step-by-step instructions for setting up browser keyword shortcuts."""
    url = f"http://localhost:{local_port}"
    return {
        "url": url,
        "chrome": {
            "name": "Chrome / Arc / Brave",
            "keyword": "evolve",
            "steps": [
                "Open Settings (⌘,) → Search engine → Manage search engines",
                'Click "Add" next to Site Search',
                f'Name: Evolve Admin  |  Keyword: evolve  |  URL: {url}',
                "Save. Now type \"evolve\" in the address bar and press Tab, then Enter.",
            ],
        },
        "firefox": {
            "name": "Firefox",
            "keyword": "evolve",
            "steps": [
                f"Navigate to {url} and bookmark it (⌘D)",
                "Right-click the bookmark in the toolbar → Properties",
                'Set the Keyword field to: evolve',
                "Now type \"evolve\" in the address bar and press Enter.",
            ],
        },
        "safari": {
            "name": "Safari",
            "steps": [
                f"Navigate to {url}",
                "File → Add to Dock… (creates a web app icon you can click anytime)",
                "Or: add a bookmark, then type part of the URL to auto-complete.",
            ],
            "note": "Safari doesn't support keyword bookmarks. The Dock shortcut is the best option.",
        },
    }
