#!/usr/bin/env python3
"""
backfill_application_tags.py — normalize and extend application_tags on every
gallery manifest in repo `gallery/`.

For each `gallery/<app>/p-*.json`:
  1. Read the existing `application_tags` (already populated for all 12 apps
     as of 2026-05-31, but with free-form values) and the optional
     `disabled_tags` list (operator dismissals).
  2. Run the canonical auto-detector over display_name + description +
     build_spec + existing tags. Skips anything in `disabled_tags`.
  3. Merge: existing tags first (preserves operator labels like
     `obsidian-integration`), then any new canonical tags from the
     vocabulary. Also drops anything in `disabled_tags` — the operator's
     dismissal is authoritative even against pre-existing manual entries.
  4. Apply per-app overrides (see _OVERRIDES below — used for suite tags and
     hand-picked additions the auto-detector misses). Overrides are also
     filtered through `disabled_tags`.
  5. Write back atomically iff tags changed.

The gallery `index.json` is regenerated as a separate step (re-run with
`--rebuild-index`), so this script is the single source of truth for
application_tags across the gallery repo state.

Usage:
    python3 scripts/backfill_application_tags.py [--dry-run] [--rebuild-index]

Idempotent — running twice in a row makes no further changes after the first.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path


_REPO_ROOT = Path(__file__).resolve().parents[1]
_GALLERY = _REPO_ROOT / "gallery"

# Make the tag_vocabulary module importable without an editable install.
_ADMIN_PKG = _REPO_ROOT / "packages" / "admin"
if str(_ADMIN_PKG) not in sys.path:
    sys.path.insert(0, str(_ADMIN_PKG))

from evolve_admin.applications.tag_vocabulary import (  # noqa: E402
    auto_detect, merge_tags,
)


# ── Per-app overrides ─────────────────────────────────────────────────────────
#
# The auto-detector is conservative (keyword-based, canonical vocab only). It
# misses tags that require context — coordinated app suites, opinionated
# audience tags, etc. Add operator-curated tags here. Keys are pkg_id; values
# are extra tags to append after the auto-detected set.
#
# Suite tags (the `*_pack` convention) live here because suites are an
# operator-level grouping, not detectable from a single app's text.

_OVERRIDES: dict[str, list[str]] = {
    # EA suite — coordinated daily executive-assistant pack.
    "p-aab5e569": ["ea-suite"],          # EA Pack
    "p-4136a932": ["ea-suite"],          # Contacts
    "p-9bfa1c84": ["ea-suite"],          # Task Manager

    # Daily-brief suite — the three "good morning" surfaces share a pack.
    "p-a9a74bf7": ["daily-brief-suite"],   # Morning Briefing
    "p-738f057c": ["daily-brief-suite"],  # Calendar Daily Summary
    "p-41e4c5f4": ["daily-brief-suite"],  # Email Triage

    # Workspace integration suite — pure data syncers that feed other apps.
    "p-fe9acef3": ["workspace-suite"],   # Calendar Sync
    "p-341576fa": ["workspace-suite"],   # Email Integration
}


def _atomic_write_text(path: Path, text: str) -> None:
    """Atomic text write via temp-file + rename. Used for the surgical
    application_tags rewrite below so we preserve every other byte of the
    source file verbatim — existing gallery JSONs have mixed
    `\\u2014` escapes and raw UTF-8 em-dashes in different fields, and
    a json.dump round-trip would normalise them and produce a 500-line
    PR diff dominated by unrelated re-encoding noise.
    """
    fd, tmp = tempfile.mkstemp(dir=path.parent, suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def _atomic_write_json(path: Path, data) -> None:
    """JSON-aware atomic write — used for gallery/index.json + tags-index.json,
    which are wholly generated by this script and have no mixed-encoding
    source to preserve."""
    fd, tmp = tempfile.mkstemp(dir=path.parent, suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


# Matches a top-level `"application_tags": [ ... ]` (or `[]`) field in a
# pretty-printed JSON manifest. Two-space indent matches the existing
# gallery files. The `[\s\S]*?` non-greedy span over the array body
# tolerates either a one-line list or a multi-line list — we don't try
# to parse the elements, we replace the whole bracket pair atomically.
_TAGS_FIELD_RE = re.compile(
    r'^(?P<indent>[ \t]*)"application_tags"\s*:\s*\[[\s\S]*?\]',
    re.MULTILINE,
)


def _rewrite_application_tags(text: str, new_tags: list[str]) -> str | None:
    """Replace the `application_tags` array in the file's text representation,
    preserving the original two-space indent and surrounding whitespace.
    Returns the rewritten text, or None if the field wasn't found.
    """
    match = _TAGS_FIELD_RE.search(text)
    if match is None:
        return None
    indent = match.group("indent")
    # Render the new tags using json.dumps (with ensure_ascii=True so any
    # non-ASCII chars get escaped to match the surrounding file convention)
    # then re-indent each line to align with the original field's column.
    rendered = json.dumps(new_tags, indent=2)
    rendered = "\n".join(
        (indent + line) if i else line
        for i, line in enumerate(rendered.splitlines())
    )
    replacement = f'{indent}"application_tags": {rendered}'
    return text[:match.start()] + replacement + text[match.end():]


def backfill_one(path: Path, dry_run: bool = False) -> tuple[bool, list[str], list[str]]:
    """Backfill a single gallery manifest.

    Returns (changed, before_tags, after_tags).
    """
    raw = path.read_text(encoding="utf-8")
    pkg = json.loads(raw)
    existing: list[str] = list(pkg.get("application_tags") or [])
    disabled: list[str] = list(pkg.get("disabled_tags") or [])

    # We deliberately omit build_spec from the blob — it's long and quotes
    # cross-app integration patterns, which trips the keyword matcher into
    # false positives (e.g. workspace-backup mentioning GitHub once in
    # passing). display_name + description + existing tags is the
    # high-signal surface; let operators add anything else by hand.
    text_blob_parts = [
        pkg.get("display_name") or "",
        pkg.get("name") or "",
        pkg.get("description") or "",
        " ".join(existing),
    ]
    auto = auto_detect(*text_blob_parts, disabled_tags=disabled)

    overrides = _OVERRIDES.get(pkg.get("pkg_id", ""), [])
    merged = merge_tags(existing, [*auto, *overrides], disabled_tags=disabled)

    if merged == existing:
        return False, existing, merged

    if not dry_run:
        rewritten = _rewrite_application_tags(raw, merged)
        if rewritten is None:
            # No existing application_tags field — fall back to a full
            # JSON dump. None of the current 12 manifests hit this branch
            # (the test_every_gallery_package_has_application_tags
            # invariant guarantees the field is present in repo files),
            # but a freshly imported gallery package without tags would.
            pkg["application_tags"] = merged
            _atomic_write_json(path, pkg)
        else:
            _atomic_write_text(path, rewritten)
    return True, existing, merged


def rebuild_index(dry_run: bool = False) -> bool:
    """Refresh gallery/index.json with denormalized application_tags + a
    sibling gallery/tags-index.json mapping tag → [pkg_id, ...].

    Returns True if anything was written.
    """
    index_path = _GALLERY / "index.json"
    tags_index_path = _GALLERY / "tags-index.json"

    entries: list[dict] = json.loads(index_path.read_text(encoding="utf-8"))
    tags_index: dict[str, list[str]] = {}

    changed_index = False
    for entry in entries:
        full_path = _GALLERY / entry["path"]
        try:
            full = json.loads(full_path.read_text(encoding="utf-8"))
        except Exception:
            continue
        tags = list(full.get("application_tags") or [])
        if entry.get("application_tags") != tags:
            entry["application_tags"] = tags
            changed_index = True
        for t in tags:
            tags_index.setdefault(t, []).append(entry["pkg_id"])

    # Stable ordering: alphabetical tag, alphabetical pkg list.
    tags_index = {
        t: sorted(set(pkgs)) for t, pkgs in sorted(tags_index.items())
    }

    existing_tags_index: dict[str, list[str]] = {}
    if tags_index_path.exists():
        try:
            existing_tags_index = json.loads(tags_index_path.read_text(encoding="utf-8"))
        except Exception:
            pass
    changed_tags_index = existing_tags_index != tags_index

    if dry_run:
        return changed_index or changed_tags_index

    if changed_index:
        _atomic_write_json(index_path, entries)
    if changed_tags_index:
        _atomic_write_json(tags_index_path, tags_index)
    return changed_index or changed_tags_index


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dry-run", action="store_true",
                   help="Print proposed changes without writing.")
    p.add_argument("--rebuild-index", action="store_true",
                   help="Also rebuild gallery/index.json + tags-index.json "
                        "from the per-app manifests.")
    args = p.parse_args()

    manifests = sorted(_GALLERY.rglob("p-*.json"))
    if not manifests:
        print(f"No manifests found under {_GALLERY}", file=sys.stderr)
        return 1

    total_changed = 0
    for path in manifests:
        if path.parent.parent != _GALLERY:
            # Only top-level per-app dirs (skip nested scripts/, etc.)
            continue
        try:
            changed, before, after = backfill_one(path, dry_run=args.dry_run)
        except Exception as exc:
            print(f"  ! {path.relative_to(_REPO_ROOT)}: {exc}", file=sys.stderr)
            continue
        rel = path.relative_to(_REPO_ROOT)
        if changed:
            total_changed += 1
            added = [t for t in after if t not in before]
            print(f"  ✓ {rel}: added {added}")
        else:
            print(f"  · {rel}: no change")

    print(f"\nBackfill: {total_changed}/{len(manifests)} manifests updated"
          + (" (dry-run)" if args.dry_run else ""))

    if args.rebuild_index:
        idx_changed = rebuild_index(dry_run=args.dry_run)
        if idx_changed:
            print(f"  ✓ gallery/index.json + gallery/tags-index.json refreshed"
                  + (" (dry-run)" if args.dry_run else ""))
        else:
            print("  · gallery/index.json + gallery/tags-index.json: no change")

    return 0


if __name__ == "__main__":
    sys.exit(main())
